"""Updated Cruz table to replace route_path with start and end points

Revision ID: ae9d0c325055
Revises: feb3eb3cdae3
Create Date: 2024-11-25 09:38:50.600149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'ae9d0c325055'
down_revision = 'feb3eb3cdae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cruz', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('start_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('start_lng', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('end_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('end_lng', sa.Float(), nullable=False))
        batch_op.drop_column('route_path')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cruz', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('route_path', sqlite.JSON(), nullable=False))
        batch_op.drop_column('end_lng')
        batch_op.drop_column('end_lat')
        batch_op.drop_column('start_lng')
        batch_op.drop_column('start_lat')

    # ### end Alembic commands ###
