"""Add difficulty to cruz

Revision ID: feb3eb3cdae3
Revises: 2a3908057a4a
Create Date: 2024-11-21 10:27:52.990072

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'feb3eb3cdae3'
down_revision = '2a3908057a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cruz', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cruz', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
